#!/bin/bash

source ~/.profile

# avoid darwin
if [[ "$OSTYPE" != "linux-gnu" ]]; then
  echo "The automated installation script does not support your OS (are you on a Mac?). You can most probably install Clover manually."
  exit
fi

version=`node -v`

if [[ "$version" != "v18.19.0" ]]; then

  # Welcome
  echo ""
  echo "Initializing Clover installer..."

  # Build Essentials
  sudo apt-get update
  sudo apt-get install build-essential -y
  sudo apt-get install python3 python3-pip -y

  # curl - nvm - Node.js - Yarn - pm2
  echo ""
  echo "Installing curl..."
  sudo apt-get install curl -y
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
  . ~/.nvm/nvm.sh
  . ~/.profile
  . ~/.bashrc
  echo "Installing Node.js 18.19.0..."
  nvm install 18.19.0
  nvm use 18.19.0
  nvm alias default 18.19.0
  echo "Installing Yarn..."
  npm i -g yarn
  echo "Installing pm2 globally..."
  yarn global add pm2
  cd scripts || exit
  yarn
  cd ../
  echo "locked" >> launcher.lock

fi

source ~/.profile

cd scripts

node ./launcher.js $1
